#!/bin/bash

echo -e "\033[0;34m[INFO]\033[0m 开始设置Git跨平台编码..."

# git status support chinese
echo "    core.quotepath=false"
git config --global core.quotepath false

echo "    i18n.commitEncoding=UTF-8"
git config --global i18n.commitEncoding UTF-8

if [ ${__IS_WIN__} = 1 ]; then
  echo "    i18n.logOutputEncoding=gbk"
  git config --global i18n.logOutputEncoding gbk
else
  echo "    i18n.logOutputEncoding=UTF-8"
  git config --global i18n.logOutputEncoding UTF-8
fi
